version: '3.1'
services:
  app:
#    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: ctrl-bet-service
    depends_on:
      - db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_USERNAME=postgres
    ports:
      - "8080:8080"
    networks:
      - app-network
  db:
    image: postgres
    restart: always
    container_name: payments-db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network: